// Need Username, githubname, Join date, Bio, Repos count, Followers count, following count, location, twitter handle, Website, company

export const mockData = {
  login: "Kijimai",
  id: 7812175,
  node_id: "MDQ6VXNlcjc4MTIxNzU=",
  avatar_url: "https://avatars.githubusercontent.com/u/7812175?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Kijimai",
  html_url: "https://github.com/Kijimai",
  followers_url: "https://api.github.com/users/Kijimai/followers",
  following_url: "https://api.github.com/users/Kijimai/following{/other_user}",
  gists_url: "https://api.github.com/users/Kijimai/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Kijimai/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Kijimai/subscriptions",
  organizations_url: "https://api.github.com/users/Kijimai/orgs",
  repos_url: "https://api.github.com/users/Kijimai/repos",
  events_url: "https://api.github.com/users/Kijimai/events{/privacy}",
  received_events_url: "https://api.github.com/users/Kijimai/received_events",
  type: "User",
  site_admin: false,
  name: "JibbyCodes",
  company: null,
  blog: "jdbucog.com",
  location: null,
  email: null,
  hireable: true,
  bio: "Studyin some codin'.\r\nLearnin' everyday.",
  twitter_username: "JonJibby",
  public_repos: 120,
  public_gists: 0,
  followers: 6,
  following: 11,
  created_at: "2014-06-06T04:17:00Z",
  updated_at: "2021-12-17T07:48:47Z",
}
